version: '3.8'

services:
  # PostgreSQL для приложения
  app-db:
    image: postgres:15-alpine
    container_name: alex-orator-app-db-local
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: alex_orator
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD:-secure_password}
    volumes:
      - alex-orator-app-db-data-local:/var/lib/postgresql/data
      - ./deployment/init-orator-app-db.sql:/docker-entrypoint-initdb.d/init-orator-app-db.sql
    ports:
      - "5434:5432"
    networks:
      - alex-orator-local-network
    restart: unless-stopped

  # Backend API (для разработки)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: alex-orator-backend-local
    environment:
      - DEBUG=true
      - APP_DATABASE_URL=postgresql://alex_orator:${APP_DB_PASSWORD:-secure_password}@app-db:5432/app_db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-jwt-secret}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
    ports:
      - "8000:8000"
    depends_on:
      - app-db
    networks:
      - alex-orator-local-network
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Alex Orator Bot (для разработки)
  orator-bot:
    build: 
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: alex-orator-bot-local
    environment:
      - BOT_TOKEN=${BOT_TOKEN:-your_telegram_bot_token_here}
      - BACKEND_URL=http://backend:8000
      - API_TIMEOUT=30
      - API_RETRY_ATTEMPTS=3
      - API_RETRY_DELAY=1
      - LOG_LEVEL=DEBUG
    depends_on:
      - backend
    networks:
      - alex-orator-local-network
    restart: unless-stopped
    volumes:
      - ./telegram-bot:/app
      - ./logs:/app/logs
    command: python orator_bot.py

  # Message Queue Worker (для разработки)
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    container_name: alex-orator-worker-local
    environment:
      - BOT_TOKEN=${BOT_TOKEN:-your_telegram_bot_token_here}
      - APP_DATABASE_HOST=app-db
      - APP_DATABASE_PORT=5432
      - APP_DATABASE_LOGIN=alex_orator
      - APP_DB_PASSWORD=${APP_DB_PASSWORD:-secure_password}
      - APP_DATABASE_NAME=app_db
      - WORKER_CHECK_INTERVAL=2
      - WORKER_BATCH_SIZE=50
      - WORKER_CONCURRENCY=10
      - WORKER_DRAIN_TIMEOUT=30
    depends_on:
      - app-db
      - orator-bot
    networks:
      - alex-orator-local-network
    restart: unless-stopped
    volumes:
      - ./worker:/app
      - ./logs:/app/logs
    command: python send_worker.py

  # Admin Panel (для разработки)
  admin-panel:
    build: 
      context: ./admin-panel
      dockerfile: Dockerfile
    container_name: alex-orator-admin-panel-local
    environment:
      # Database Configuration
      - DB_HOST=app-db
      - DB_PORT=5432
      - DB_NAME=app_db
      - DB_USER=alex_orator
      - APP_DB_PASSWORD=${APP_DB_PASSWORD:-secure_password}
      # Security Configuration
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-jwt-secret}
      # Security Settings
      - MAX_LOGIN_ATTEMPTS=5
      - LOGIN_TIMEOUT_MINUTES=15
      - SESSION_TIMEOUT_MINUTES=30
      - BCRYPT_ROUNDS=12
      # Streamlit Configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=true
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      # Logging
      - LOG_LEVEL=INFO
    ports:
      - "8501:8501"
    depends_on:
      - app-db
      - backend
    networks:
      - alex-orator-local-network
    restart: unless-stopped
    volumes:
      - ./admin-panel:/app
      - ./logs:/app/logs
    command: streamlit run ui/admin_app.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=true --server.enableXsrfProtection=false

volumes:
  alex-orator-app-db-data-local:
    driver: local

networks:
  alex-orator-local-network:
    driver: bridge 